# Generated by Django 5.0 on 2024-03-12 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_exam', '0002_notepad'),
        ('subject', '0004_studentenrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
    ]
