# Generated by Django 5.0 on 2024-03-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_exam', '0003_examdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetail',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
