# Generated by Django 5.0 on 2024-03-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_exam', '0004_examdetail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetail',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
